#!/bin/bash

main=$(head -1 /data/.mainclass)

read -r -d '' input <<- EOF
Jan Lana
Pepa Zdepa
Jara Cimrman
Kejchal Trpaslik
Premysl Orac
Ruzenka Sipkova
Bozena Nemcova
Anezka Ceska
Marie Terezie
Eliska Pomoranska
EOF

read -r -d '' output <<- EOF
Anezka Ceska Bozena Nemcova Eliska Pomoranska Jan Lana Jara Cimrman Kejchal Trpaslik Marie Terezie Pepa Zdepa Premysl Orac Ruzenka Sipkova
Anezka Ceska Jara Cimrman Jan Lana Bozena Nemcova Premysl Orac Eliska Pomoranska Ruzenka Sipkova Marie Terezie Kejchal Trpaslik Pepa Zdepa
EOF

echo "$ java $main"
echo "// ===== vstup ====="
cat <<<"$input"

out1=$(cd /data/build; java "$main" <<<"$input") || exit 11
echo "// ===== vystup ====="
head -c 800 <<<"$out1"

out1_filtered=$(grep -f <(echo "$input") <<<"$out1")

[[ -z $(comm -2 -3 <(xargs <<<"$out1" | tr ' ' '\n' | sort -u ) <(xargs <<<"$output" | tr ' ' '\n' | sort -u)) ]] || { \
	echo -e "\nChyba: výstup obsauje i jiná slova než zadaná jména"; }

if [[ $(xargs <<<"$out1_filtered") != $(xargs <<<"$output") ]]
then
	echo -e "\nChyba: špatné pořadí jmen"
	exit 11
fi
