#!/bin/bash

[[ -d /data/unpack && -d /data/unpack_all ]] || exit 0

cp -r /data/unpack /data/unpack_all/000

n=0
while read percent answer
do
	[[ $n -ne 0 ]] || echo "Podobné řešení odevzdal:"
	n=$((n+1))
	echo "  $n. $answer ($percent)"
done < <(java -jar /lib/jplag.jar /data/unpack_all 2>/dev/null | perl -nle 'next unless /^Comparing 000-(.+): ([0-9.]+)/; print "$2 $1"  if $2>90' | sort -rV | head -n 4)
